replicaCount: 1
image:
  tag: main
  pullPolicy: Always
ingress:
  hosts:
    - host: pbotapps-test.portland.gov
      paths:
        - /graphql
  tls:
    - secretName: pbotapps-test-portland-gov-tls
      hosts:
        - pbotapps-test.portland.gov
