kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
{{- (.Files.Glob ".secret/*").AsSecrets | nindent 2 }}