name: Push main build

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      REPOSITORY: ${{ secrets.ACR_NAME }}.azurecr.io
      IMAGE: graphql-server
    steps:
      - uses: actions/checkout@v2
      - name: Tezt Azure CLI
        run: az --version
      - name: Log in to Azure Container Registry
        run: |
            az login --service-principal -u ${{ secrets.AZURE_CREDENTIALS.clientId }} -p ${{ secrets.AZURE_CREDENTIALS.clientSecret }} --tenant ${{ secrets.AZURE_CREDENTIALS.tenantId }}
            az acr login --name ${{ secrets.ACR_NAME }}
      - name: Run Docker build
        run: docker build -t $REPOSITORY/$IMAGE:main .
      - name: Push image to repository
        run: docker push $REPOSITORY/$IMAGE:main
