name: Push main build

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      REPOSITORY: ${{ secrets.ACR_NAME }}.azurecr.io
      IMAGE: graphql-server
    steps:
      - uses: actions/checkout@v2
      - name: Test Azure CLI
        run: az --version
      - name: Log in to Azure Container Registry
        env:
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CREDENTIALS.clientId }}
            AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CREDENTIALS.clientSecret }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_CREDENTIALS.tenantId }}
            AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_CREDENTIALS.subscriptionId }}
        run: |
            az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
            az account set --subscription $AZURE_SUBSCRIPTION_ID
            az acr login --name ${{ secrets.ACR_NAME }}
      - name: Run Docker build
        run: docker build -t $REPOSITORY/$IMAGE:main .
      - name: Push image to repository
        run: docker push $REPOSITORY/$IMAGE:main
